# Generated by Django 4.1.3 on 2022-11-02 14:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(16, message='to low age')], verbose_name='age')),
                ('gender', models.CharField(choices=[(0, 'male'), (1, 'female')], max_length=6, verbose_name='gender')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='student', to='education.studygroup', verbose_name='group')),
            ],
        ),
    ]
