# Generated by Django 4.1.3 on 2022-11-02 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='title')),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='direction', to='personnel.curator', verbose_name='curator')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='title')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline', to='education.direction', verbose_name='direction')),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3, verbose_name='number')),
                ('vacancies', models.IntegerField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='discipline', to='education.discipline', verbose_name='discipline')),
            ],
        ),
    ]
