# Generated by Django 4.1.3 on 2022-11-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='vacancies',
        ),
    ]
