# Generated by Django 4.1.3 on 2022-11-05 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_alter_curator_user'),
        ('education', '0002_remove_studygroup_vacancies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='curator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='direction', to='personnel.curator', verbose_name='curator'),
        ),
    ]
